apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260523-234617-z7yo7j0aljqh-service
spec:
  selector:
    app: enterprise-system-20260523-234617-z7yo7j0aljqh
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
